### ISSUE TITLE
Add option for full white/black background

### ISSUE THREAD

**Issue by gilbertohasnofb** [wei/socialify#93]
The backgrounds available are nice but somewhat busy. It would be great to have the option to disable these patterns and have a full white/black background.

**Comment by CryogenicPlanet** [comment]
@gilbertohasnofb Definitely a good idea, and happy to accept a PR for the same.

A good starting point would be below, where you can make a conditional check for the pattern. 

The easiest way I can see to do this is to add a `pattern` called solid which will reflect the chosen theme.


https://github.com/wei/socialify/blob/beeba2dc65beae3171a06fbc71063513734309fd/common/types/configType.ts#L7-L17

If the pattern isn't in the below mapping it will return a solid already, so you can use that too

https://github.com/wei/socialify/blob/beeba2dc65beae3171a06fbc71063513734309fd/common/helpers.ts#L55-L57

**Comment by gilbertohasnofb** [comment]
@CryogenicPlanet Hi, thanks for the detailed suggestion. I installed `yarn` on my system but I'm running into some issues trying to build locally and I'll need to investigate it a bit further. `$ yarn install` runs fine, but `$ yarn build` gives me a build error:

```
$ yarn build                                                           
yarn run v1.22.5                                                                                                        
$ next build                                                                                                            
info  - Loaded env from /home/gilberto/Desktop/socialify/.env                                                           
                                                                                                                        
> Build error occurred
{ Error: Cannot find module 'webpack/lib/RawModule'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.mod._resolveFilename (/home/gilberto/Desktop/socialify/node_modules/next/dist/build/webpack/require-hook
.js:4:1855)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/gilberto/Desktop/socialify/node_modules/google-fonts-plugin/dist/Chunk/Chunk.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12) code: 'MODULE_NOT_FOUND' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Would you have any idea what might be the issue?

**Comment by CryogenicPlanet** [comment]
Hey @gilbertohasnofb please checked out https://github.com/wei/socialify#development

Essentially you need to set up your local env variables

**Comment by wei** [comment]
@gilbertohasnofb it seems to be a problem on `google-fonts-plugin` dependency. We need to find an alternative that is being kept up-to-date.
